apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
    - list:
        elements:
          - name: secrets-store-csi-driver
            chart: secrets-store-csi-driver
            repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
            namespace: kube-system
            targetRevision: 1.4.7

  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          values: |
            syncSecret:
              enabled: true
            enableSecretRotation: false
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store-provider
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
    - list:
        elements:
          - name: secrets-store-aws-provider
            chart: secrets-store-csi-driver-provider-aws
            repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
            namespace: kube-system
            targetRevision: 0.3.9
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: "3"
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
        helm:
          values: |
            fullnameOverride: secrets-store-aws-provider
            serviceAccount:
              create: false
            secrets-store-csi-driver:
              install: false
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true