---
# Application 1: Prometheus Stack (Adopts Helm release)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 67.4.0
    helm:
      releaseName: prom-stack  
      skipCrds: true           
      values: |
        grafana:
          enabled: true
          adminPassword: ${GRAFANA_PASS}
          service:
            type: LoadBalancer
            port: 80
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        
        prometheus:
          prometheusSpec:
            retention: 30d
        
        alertmanager:
          enabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m

---
# Application 2: Custom Monitoring Config
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-custom-config
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/sahar449/DevOps.git
    targetRevision: HEAD
    path: ArgoCD/monitoring
    helm:
      parameters:
        - name: alertmanager.password
          value: "${GOOGLE_SECRET_PROM}"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m