apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  sources:
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 67.4.0
      helm:
        values: |
          grafana:
            enabled: true
            adminPassword: "${GRAFANA_PASS}"
            service:
              type: LoadBalancer
              port: 80
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
                service.beta.kubernetes.io/aws-load-balancer-name: grafana-clb
                service.beta.kubernetes.io/aws-load-balancer-type: classic
          
          prometheus:
            service:
              type: ClusterIP
            prometheusSpec:
              replicas: 1
              retention: 30d
          
          alertmanager:
            enabled: true
            service:
              type: ClusterIP
            alertmanagerSpec:
              replicas: 1
          
          prometheusOperator:
            admissionWebhooks:
              enabled: false
    
    - repoURL: https://github.com/sahar449/DevOps.git
      targetRevision: HEAD
      path: ArgoCD/monitoring/templates
      directory:
        recurse: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 3m