apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  sources:
    # Source 1: Prometheus Helm Chart
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 67.4.0
      helm:
        values: |
          grafana:
            enabled: true
            adminPassword: "${GRAFANA_PASS}"
            service:
              type: LoadBalancer
              port: 80
              annotations:
                service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          
          prometheus:
            prometheusSpec:
              retention: 30d
          
          alertmanager:
            enabled: true
    
    # Source 2: Custom Configs 
    - repoURL: https://github.com/sahar449/DevOps.git
      targetRevision: HEAD
      path: ArgoCD/monitoring/templates
      directory:
        recurse: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 1m
