apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: fluent-bit
            chart: aws-for-fluent-bit
            version: "0.1.34"
            namespace: kube-system
            saName: fluent-bit
            roleArn: arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/eks-fluent-bit-role

          - appName: cloudwatch-agent
            chart: aws-cloudwatch-metrics
            version: "0.0.9"
            namespace: amazon-cloudwatch
            saName: cloudwatch-agent
            roleArn: arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/eks-cloudwatch-agent-role

  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default

      source:
        repoURL: https://aws.github.io/eks-charts
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          values: |
            clusterName: eksdemo-cluster
            region: us-west-2

            serviceAccount:
              create: true
              name: {{saName}}
              annotations:
                eks.amazonaws.com/role-arn: {{roleArn}}

            cloudWatchLogs:
              enabled: true
              logGroupName: /aws/eks/eksdemo-cluster/logs
              autoCreateGroup: false

            firehose:
              enabled: false
            kinesis:
              enabled: false

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
