apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-stack
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: fluent-bit # sa name
            chart: aws-for-fluent-bit
            version: "0.1.34"
            namespace: kube-system
            roleName: eks-fluent-bit-role # aws iam role
            
          - name: cloudwatch-agent # sa name
            chart: aws-cloudwatch-metrics
            version: "0.0.9"
            namespace: amazon-cloudwatch
            roleName: eks-cloudwatch-agent-role # aws iam role
  
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      
      source:
        repoURL: https://aws.github.io/eks-charts
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          values: |
            clusterName: eksdemo-cluster
            region: us-west-2
            serviceAccount:
              create: true
              name: '{{name}}'
              annotations:
                eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_NUMBER}:role/{{roleName}}
            cloudWatchLogs:
              enabled: true
              logGroupName: /aws/eks/demo-cluster/logs
              autoCreateGroup: true
            firehose:
              enabled: false
            kinesis:
              enabled: false
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true