apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.providerClassName }}
spec:
  provider: aws
  parameters:
    region: us-west-2
    objects: |
      - objectName: "rds-creds"
        objectType: "secretsmanager"
        jmesPath:
          - path: "host"
            objectAlias: "host"
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
          - path: "dbname"
            objectAlias: "dbname"