apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-app-sa
  namespace: default
  annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::{{.Values.secrets.accountNumber}}:role/flask-app-secrets-role"
