apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-app-alerts
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  groups:
    - name: flask-app-alerts
      interval: 5s
      rules:
        - alert: FlaskAppPodDown
          expr: kube_deployment_status_replicas_available{namespace="default", deployment="flask-app"} < 2
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: "Flask App Pod Down!"
            description: "Flask App has less than 2 pods running"
