apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-stack-kube-prom-alertmanager
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'saharr449@gmail.com'
      smtp_auth_username: 'saharr449@gmail.com'
      smtp_auth_password: {{ .Values.alertmanager.password | quote }}
      smtp_require_tls: true
    
    route:
      receiver: 'email'
      group_by: ['alertname', 'namespace']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
    
    receivers:
      - name: 'email'
        email_configs:
          - to: 'saharr449@gmail.com'
            send_resolved: true
            headers:
              Subject: '🚨 Kubernetes Alert: {{`{{ .GroupLabels.alertname }}`}}'
            html: |
              <h2>{{`{{ .Status | toUpper }}`}}</h2>
              {{`{{ range .Alerts }}`}}
              <p><b>Alert:</b> {{`{{ .Labels.alertname }}`}}</p>
              <p><b>Description:</b> {{`{{ .Annotations.description }}`}}</p>
              <p><b>Pod:</b> {{`{{ .Labels.pod }}`}}</p>
              <p><b>Namespace:</b> {{`{{ .Labels.namespace }}`}}</p>
              {{`{{ end }}`}}